spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
